base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('medidores.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [path(r'static/(?P<path>.*)', serve, {'document_root': settings.STATIC_ROOT}),
                    path(r'media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}) ]

medidores/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('accounts/login/', login_view, name='login'),
    path('accounts/signup/', signup_view, name='signup'),
    path('logout/', logout_view, name='logout'),
    path('reset_password/', reset_password_view, name='resset_password'),
    path('change_password/', change_password_view, name='change_password'),
]

medidores/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    cedula = models.CharField(max_length=10, unique=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    celular = models.CharField(max_length=10, null=True, blank=True)

    def __str__(self):
        if self.first_name and self.last_name:
            return self.first_name + ' ' + self.last_name + ' - ' + self.cedula
        return self.username
    
    class Meta:
        unique_together = ('cedula', 'email')
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'


class Medidor(models.Model):

    CHOICE_TIPO_CONSUMO = (
        ('Residencial', 'Residencial'),
        ('Comercial', 'Comercial'),
        ('Industrial', 'Industrial'),
    )

    # cedula = models.CharField(max_length=10)
    numero_medidor = models.CharField(max_length=10, unique=True)
    cliente = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    direccion = models.CharField(max_length=100)
    tipo_consumo = models.CharField(max_length=20, choices=CHOICE_TIPO_CONSUMO)
    meses_deuda = models.IntegerField(default=0)
    consumo = models.FloatField(default=0)
    valor_mes = models.FloatField(default=0)
    total_deuda = models.FloatField(default=0)

    def __str__(self):
        return self.numero_medidor
    
    class Meta:
        unique_together = ('numero_medidor', 'cliente')
        verbose_name = 'Medidor'
        verbose_name_plural = 'Medidores'

medidores/forms.py
from django import forms
from django.utils.safestring import mark_safe
from .models import CustomUser

class BaseForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            self.configure_field(field)

        try:
            errorList=list(self.errors)
            for item in errorList:
                self.fields[item].widget.attrs.update({'autofocus': ''})
                break
        except:
            pass

    def configure_field(self, field):
        if "class" in field.widget.attrs:
            field.widget.attrs["class"] += " form-control form-control-sm"
        else:
            field.widget.attrs["class"] = "form-control form-control-sm"

        # Check if field.widget has input_type attribute
        if hasattr(field.widget, "input_type"):
            if field.widget.input_type == "checkbox":
                field.widget.attrs["class"] = field.widget.attrs["class"].replace("form-control form-control-sm", "form-check-input")
            if field.widget.input_type == "select":
                field.widget.attrs["class"] += " form-select"

        if "validate" in field.widget.attrs:
            validation_attrs = self.get_validation_attrs(field.widget.attrs["validate"])
            field.widget.attrs.update(validation_attrs)

        if field.required:
            field.label = mark_safe(field.label + '<span class="text-danger">*</span> ')


    def get_validation_attrs(self, validation_type):
        validation_attrs = {}
        if validation_type == "telefono_movil":
            validation_attrs['pattern'] = "[0]{1}[9]{1}[0-9]{8}"
            validation_attrs['validate'] = "Núm. móvil incorrecto. Ejm: 0987654321"
        elif validation_type == "telefono_fijo":
            validation_attrs['pattern'] = "[0]{1}[2-8]{1}[0-9]{7}"
            validation_attrs['validate'] = "Núm. fijo incorrecto. Ejm: 022345678"
        elif validation_type == "cedula":
            validation_attrs['pattern'] = "[0-9]{10}"
            validation_attrs['validate'] = "La cédula debe tener 10 dígitos"
        elif validation_type == "email":
            validation_attrs['pattern'] = "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$"
            validation_attrs['validate'] = "Correo electrónico incorrecto."
        return validation_attrs


class ModelBaseForm(BaseForm, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ModelBaseForm, self).__init__(*args, **kwargs)


class CustomUserForm(ModelBaseForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'email', 'cedula', 'fecha_nacimiento', 'celular']
        labels = {
            'username': 'Usuario',
            'first_name': 'Nombres',
            'last_name': 'Apellidos',
            'email': 'Correo Electrónico',
            'cedula': 'Cédula',
            'fecha_nacimiento': 'Fecha de Nacimiento',
            'celular': 'Celular',
        }
        widgets = {
            'fecha_nacimiento': forms.DateInput(attrs={'type': 'date'}),
        }

class LoginForm(BaseForm):
    cedula = forms.CharField(label='Cédula Identidad', max_length=150)
    password = forms.CharField(label='Contraseña', widget=forms.PasswordInput())


class SignupForm(BaseForm):
    cedula = forms.CharField(label='Cédula Identidad', max_length=10)
    first_name = forms.CharField(label='Nombres', max_length=150)
    last_name = forms.CharField(label='Apellidos', max_length=150)
    email = forms.EmailField(label='Correo Electrónico')
    email2 = forms.EmailField(label='Confirmar Correo Electrónico')
    fecha_nacimiento = forms.DateField(label='Fecha de Nacimiento', widget=forms.DateInput(attrs={'type': 'date'}))
    celular = forms.CharField(label='Celular', max_length=10)
    password = forms.CharField(label='Contraseña', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Confirmar Contraseña', widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super(SignupForm, self).clean()
        email = cleaned_data.get('email')
        email2 = cleaned_data.get('email2')
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if email != email2:
            self.add_error('email2', 'Los correos electrónicos no coinciden')
        if password != password2:
            self.add_error('password2', 'Las contraseñas no coinciden')
        return cleaned_data
    

class ResetPasswordForm(BaseForm):
    email = forms.EmailField(label='Correo Electrónico')

class ChangePasswordForm(BaseForm):
    password = forms.CharField(label='Contraseña Nueva', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Confirmar Contraseña', widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super(ChangePasswordForm, self).clean()
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if password != password2:
            self.add_error('password2', 'Las contraseñas no coinciden')
        return cleaned_data

medidores/views/change_password.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required

from medidores.models import CustomUser
from medidores.forms import ChangePasswordForm

from medidores.utils import enviar_correo_electronico_asincrono, generar_contrasena

@login_required
def change_password_view(request, *args, **kwargs):

    context = {}
    
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data.get('password')

            usuario = request.user
            usuario.set_password(password)
            usuario.save()

            messages.success(request, 'Contraseña actualizada correctamente')
            return redirect('home')
        else:
            context['form'] = form
            return render(request, 'medidores/change_password.html', context)      
        
    else:
        form = ChangePasswordForm()
        context['form'] = form
        return render(request, 'medidores/change_password.html', context)

medidores/views/home.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required

from medidores.models import CustomUser, Medidor

@login_required
def home(request, *args, **kwargs):
    context = {}
    if request.method == 'POST':
        if request.POST.get('logout'):
            return redirect('logout')
        
    else:
        usuario = CustomUser.objects.get(pk=request.user.id)
        medidores = Medidor.objects.filter(cliente=usuario)
        context['medidores'] = medidores
        return render(request, 'medidores/home.html', context)

medidores/views/login.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.core.mail import send_mail

from medidores.models import CustomUser
from medidores.forms import LoginForm

from medidores.utils import enviar_correo_electronico_asincrono

def login_view(request, *args, **kwargs):

    context = {}

    if request.user.is_authenticated:
        return redirect('home')
    
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                request,
                username =form.cleaned_data['cedula'],
                password=form.cleaned_data['password']
            )
            if user is not None:
                login(request, user)
                enviar_correo_electronico_asincrono(
                    'Inicio de Sesión',
                    'Se ha iniciado sesión en el sistema',
                    ['juan.ingaor@gmail.com']
                )
                return redirect('home')
            else:
                form.add_error(None, 'Cédula o contraseña incorrectos')
                context['form'] = form
                return render(request, 'medidores/login.html', context)
        else:
            context['form'] = form
            return render(request, 'medidores/login.html', context)
            
        
    else:
        form = LoginForm()
        context['form'] = form
        return render(request, 'medidores/login.html', context)

medidores/views/logout.py
from django.shortcuts import redirect, render
from django.contrib.auth import logout

def logout_view(request, *args, **kwargs):
    if request.user.is_authenticated:
        logout(request)
        return redirect('login')
    else:
        return redirect('login')

medidores/views/reset_password.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.core.mail import send_mail

from medidores.models import CustomUser
from medidores.forms import ResetPasswordForm

from medidores.utils import enviar_correo_electronico_asincrono, generar_contrasena

def reset_password_view(request, *args, **kwargs):

    context = {}

    if request.user.is_authenticated:
        return redirect('home')
    
    if request.method == 'POST':
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            user = CustomUser.objects.filter(email=email).first()
            if user is not None:
                # Cambia la contraseña del usuario
                nueva_contraseña = generar_contrasena(10)
                user.set_password(nueva_contraseña)
                user.save()

                enviar_correo_electronico_asincrono(
                    'Restablecimiento de Contraseña',
                    'Se ha solicitado un restablecimiento de contraseña. Su nueva contraseña es: {}'.format(nueva_contraseña),
                    [user.email]
                )
                messages.success(request, 'Se ha enviado un correo electrónico con las instrucciones para restablecer la contraseña')
                return redirect('login')
            else:
                form.add_error(None, 'No se ha encontrado un usuario con el email proporcionada')
                context['form'] = form
                return render(request, 'medidores/reset_password.html', context)
        else:
            context['form'] = form
            return render(request, 'medidores/reset_password.html', context)      
        
    else:
        form = ResetPasswordForm()
        context['form'] = form
        return render(request, 'medidores/reset_password.html', context)

medidores/views/signup.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login

from medidores.models import CustomUser

from medidores.forms import SignupForm

def signup_view(request, *args, **kwargs):
    context = {}
    if request.user.is_authenticated:
        return redirect('home')
    
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            cedula = form.cleaned_data['cedula']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            fecha_nacimiento = form.cleaned_data['fecha_nacimiento']
            celular = form.cleaned_data['celular']
            password = form.cleaned_data['password']

            if CustomUser.objects.filter(cedula=cedula).exists():
                form.add_error('cedula', 'La cédula ya está registrada')
                context['form'] = form
                return render(request, 'medidores/signup.html', context)
            
            if CustomUser.objects.filter(email=email).exists():
                form.add_error('email', 'El correo electrónico ya está registrado')
                context['form'] = form
                return render(request, 'medidores/signup.html', context)

            user = CustomUser.objects.create_user(
                username=cedula,
                email=email,
                password=password,
                cedula=cedula,
                first_name=first_name,
                last_name=last_name,
                fecha_nacimiento=fecha_nacimiento,
                celular=celular
            )

            login(request, user)
            return redirect('home')
        else:
            context['form'] = form
            return render(request, 'medidores/signup.html', context)
        
    else:
        form = SignupForm()
        context['form'] = form
        return render(request, 'medidores/signup.html', context)

medidores/templates/medidores/change_password.html
{% extends 'medidores/layout.html' %}

{% block content %}
<div class="container py-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">Cambiar Contraseña</h3>
                </div>
                <div class="card-body">
                    <form method="post" action="{{ request.path }}">
                        {% csrf_token %}
                        {% include 'medidores/forms/formRender.html' %}
                        <div class="my-3 d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">Cambiar Contraseña</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

medidores/templates/medidores/home.html
{% extends 'medidores/layout.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center mt-3">Bienvenido a Medidores</h1>
            </div>
            {% for medidor in medidores %}
                <div class="col-md-4">
                    <div class="card my-3">
                        <div class="card-header">
                            <h3 class="mb-0">{{ medidor.numero_medidor }}</h3>
                        </div>
                        <div class="card-body">
                            <p>Dirección: {{ medidor.direccion }}</p>
                            <p>Tipo de Consumo: {{ medidor.get_tipo_consumo_display }}</p>
                            <p>Meses de Deuda: {{ medidor.meses_deuda }}</p>
                            <p>Consumo: {{ medidor.consumo }}</p>
                            <p>Valor Mes: {{ medidor.valor_mes }}</p>
                            <p class="mb-0">Total Deuda: {{ medidor.total_deuda }}</p>
                        </div>
                    </div>
                </div>
            {% empty %}
                <div class="col-md-12">
                    <p class="text-center mt-5">No hay medidores registrados</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

medidores/templates/medidores/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width" />
        <meta name="facebook-domain-verification" content="6eoe57s1xtul14z6qqxi0aagaaq82o" />
        <meta name="keywords" content="medidores"/>
        <meta name="robots" content="index, follow"/>
        <meta name="language" content="Spanish"/>
        <meta property="og:site_name" content="Medidores"/>

        {% block css %}
            <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/styles.css' %}"> 
            <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" /> 
            {% block extracss %}
            {% endblock extracss %}
        {% endblock css %}
    </head>
    <body>

        {% comment %} ******************************** {% endcomment %}

        <nav class="navbar navbar-expand-md bg-light">
            <div class="container-fluid">
                <a title="Inicio" class="navbar-brand h6 mb-0 d-flex align-items-center gap-1" href="/">
                    <span class="small">Medidores</span>
                </a>
                <div>
                    {% if user.is_authenticated %}
                        <a title="Perfil" class="btn btn-primary" href="{% url 'change_password' %}">
                            <i class="fas fa-user"></i> Cambiar Contraseña
                        </a>

                        <a title="Cerrar Sesión" class="btn btn-secondary" href="{% url 'logout' %}">
                            <i class="fas fa-sign-out-alt"></i> Cerrar Sesión
                        </a>
                    {% else %}
                        <a title="Iniciar Sesión" class="btn btn-primary" href="{% url 'login' %}">
                            <i class="fas fa-sign-in-alt"></i> Iniciar Sesión
                        </a>
                    {% endif %}
                </div>
            </div>
        </nav>

        {% comment %} Alertas y mensajes en el feed principal {% endcomment %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}

        {% comment %} Contanido Principal {% endcomment %}
        {% block content %}
        {% endblock content %}
    </body>

    <footer class="bg-light">

        {% comment %} {% include 'partials/footer.html' %} {% endcomment %}

        {% block javascript %}
            <script src="{% static 'bootstrap/bootstrap.bundle.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'assets/js/functions.js' %}"></script> 
            {% block extrajs %}
            {% endblock extrajs %}
        {% endblock javascript %}
    </footer>
</html>

medidores/templates/medidores/login.html
{% extends 'medidores/layout.html' %}

{% block content %}
<div class="container py-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center mb-0">Iniciar Sesión</h3>
                </div>
                <div class="card-body">
                    
                    <p class="text-center mb-5">¿No tienes una cuenta? <a class="link-primary" href="{% url 'signup' %}">Regístrate</a></p>
                    
                    <form method="post" action="{{ request.path }}">
                        {% csrf_token %}
                        {% include 'medidores/forms/formRender.html' %}
                        <div class="my-3 d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
                        </div>
                        <div class="d-flex justify-content-center">
                            <a href="{% url 'resset_password' %}" class="btn btn-link"><i class="fa-solid fa-lock"></i> ¿Olvidaste tu contraseña?</a>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

medidores/templates/medidores/reset_password.html
{% extends 'medidores/layout.html' %}

{% block content %}
<div class="container py-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">Restablecer Contraseña</h3>
                </div>
                <div class="card-body">
                    <p>¿Ha olvidado su contraseña? Introduzca su correo electrónico y le enviaremos un correo que le permitirá restablecerla.</p>

                    <form method="post" action="{{ request.path }}">
                        {% csrf_token %}
                        {% include 'medidores/forms/formRender.html' %}
                        <div class="my-3 d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">Enviar Clave de Recuperación</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

medidores/templates/medidores/signup.html
{% extends 'medidores/layout.html' %}

{% block content %}
<div class="container py-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">Registrarse</h3>
                </div>
                <div class="card-body">
                    
                    <p class="text-center mb-5">¿Ya tienes una cuenta? <a class="link-primary" href="{% url 'login' %}">Iniciar Sesión</a></p>

                    <form method="post" action="{{ request.path }}">
                        {% csrf_token %}
                        {% include 'medidores/forms/formRender.html' %}
                        <div class="my-3 d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">Registrarse</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}